version: '3'

services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true --providers.docker"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"

      #SSL let`s sEncrypts
      - "--entrypoints.https.http.tls.certResolver=le"
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.email=akulllvlllad@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      # The HTTP port
      - "80:80"
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - ./data/letsencrypt:/letsencrypt
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock